global using Adnc.Demo.Shared.Const.Entity.Usr;
global using Adnc.Demo.Usr.Repository.Entities;
global using Adnc.Infra.IRepository;
global using Adnc.Shared;
global using Adnc.Shared.Repository.EfEntities;
global using Adnc.Shared.Repository.EfEntities.Config;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Reflection;
